apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: tls-route
spec:
  parentRefs:
    - name: eg
  hostnames:
    - "app.tls.prod"
  rules:
    - backendRefs:
        - name: backend-prod-svc
          port: 80
